NutriWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from Webapp import views

handler404 = 'Webapp.views.handler404'
handler500 = 'Webapp.views.handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

Webapp/urls.py
from django.urls import path
from Webapp import views

# SET THE NAMESPACE!
app_name = 'Webapp'

urlpatterns = [
    path('order/',views.order,name='order'),
    path('user_login/',views.user_login,name='user_login'),
    path('logout/',views.user_logout,name='user_logout'),
    path('register/',views.register,name='register'),
    path('', views.mainpage, name='services'),
    path('order/', views.order, name='order'),
    path('thanks/',views.thanks,name='thanks'),
    path('userinfo/',views.userinfo,name='userinfo'),
    path('db/',views.dbfront,name='dbfront'),
]

shopping_cart/urls.py
from django.conf.urls import url
from django.urls import path

from .views import (
    add_to_cart,
    order_details,
    delete_from_cart,
    update_item_number,
    export,
    
)

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^service/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^service/update/(?P<item_id>[-\w]+)/(?P<item_number>[-\w]+)/$', update_item_number, name='update_item'),
    path('export/',export,name='export'),

    
]

shopping_cart/models.py
from django.db import models

from Webapp.models import Services
from Webapp.models import Profile

class ServiceItem(models.Model):
    service = models.ForeignKey(Services, on_delete=models.SET_NULL,null=True)
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    number_of_samples= models.IntegerField(default=1)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered= models.DateTimeField(null=True)

    def __str__(self):
        return self.service.description

class OrderServices(models.Model):
    ref_code= models.CharField(max_length=15)
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(ServiceItem)
    date_ordered = models.DateTimeField(auto_now=True)

    def get_cart_items(self):
        return self.items.all()

    def __str__(self):
        return '{0} - {1}'.format(self.owner, self.ref_code)

shopping_cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from Webapp.models import Profile
from Webapp.forms import MessageForm
from Webapp.models import Services
from shopping_cart.models import OrderServices, ServiceItem
from django.urls import reverse
from django.http import HttpResponse
from Webapp.models import Services
import csv, datetime
from django.utils.crypto import get_random_string


def get_user_pending_order(request):
    user_profile = get_object_or_404(Profile, user=request.user)
    order = OrderServices.objects.filter(owner = user_profile, is_ordered=False)
    if order.exists():
        return order[0]
    return 0


@login_required(login_url='/user_login/')
def add_to_cart (request, **kwargs):
    services = Services.objects.all()
    #filtered_services = OrderServices.objects.filter(owner=request.user.profile, is_ordered=False)
    user_profile = get_object_or_404(Profile, user=request.user)

    form = MessageForm()
    service = Services.objects.filter(id=kwargs.get('item_id',"")).first()
    if service in request.user.profile.services.all():
        messages.info(request, "You already added this service")
   
    service_item, status = ServiceItem.objects.get_or_create(service=service, owner=user_profile, is_ordered=False)


    user_order, status = OrderServices.objects.get_or_create(owner=user_profile, is_ordered=False)
    user_order.items.add(service_item)

    if status:
        code = "NT_" + get_random_string(4)+ str(datetime.datetime.now().time())[0:2]
        user_order.ref_code= code
        user_order.save()

    context = {'form':form,'services':services}
    return redirect(reverse('Webapp:order'))

@login_required(login_url='/user_login/')
def order_details(request, **kwargs):
    existing_order = get_user_pending_order(request)
    context = {
        'order': existing_order
    }
    return render(request, 'shopping_cart/order_summary.html', context)

@login_required(login_url='/user_login/')
def delete_from_cart(request, item_id):
    user_profile = get_object_or_404(Profile, user=request.user)
    item_to_delete = ServiceItem.objects.filter(pk=item_id, owner=user_profile)
    if item_to_delete.exists():
        item_to_delete[0].delete()
        messages.info(request, "Item has been deleted")
    return redirect(reverse('shopping_cart:order_summary'))

@login_required(login_url = '/user_login/')
def update_item_number(request, **kwargs):
    item_id = kwargs.get('item_id', "10")
    item_number = kwargs.get('item_number', "10")
    item_to_update = get_object_or_404(ServiceItem, pk=item_id)
    item_to_update.number_of_samples= item_number
    item_to_update.save(update_fields=["number_of_samples"])
    return redirect(reverse('shopping_cart:order_summary')) 


@login_required(login_url = '/user_login/')
def export(request):
    user_profile = get_object_or_404(Profile, user=request.user)
    order = OrderServices.objects.filter(owner = user_profile, is_ordered=False)

    response=  HttpResponse(content_type='text/csv')
    len_items = len(order.values_list('items__service__description'))
    our_array = ['Service Name','Number of Samples']
    for i in range(1,len_items+1):
        our_array.append('SampleNames#'+str(i))
    writer = csv.writer(response)
    writer.writerow(our_array)

    #order_object = order._meta_get_field('items__number_of_samples')

    for my_order in order.values_list('items__service__description','items__number_of_samples'):
        #ourTuple = tuple()
        #for value in  range (1,my_order[1]+1):
            #ourTuple = ourTuple + ('sample' + str(value),)

        writer.writerow(my_order  ) #+ ourTuple) 
    
    file_name= order.values_list('ref_code')[0][0]

    response['Content-Disposition'] = 'attachment; filename=' + file_name + '.csv'
    
    return response




    

shopping_cart/templates/shopping_cart/order_summary.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block body %}


<section id="intro" class=" clearfix">
   <div class=" container d-flex h-100">
     <div class="row justify-content-center align-self-center">
    <table class="table table-hover table-bordered text-center">
      <tr class="text-center">
        <th>no.</th>
        <th>Service</th>
        <th>Number of Samples</th>
        <th>Actions</th>
      </tr>
      {% for item in order.get_cart_items %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>
            {{ item.service.description }}
            
          </td>
          <td>
            <input type="number" class="quantity" name="quantity" min="1" value= {{item.number_of_samples}}>
          </td>
          <td>
              <a class="myLink" href="#" onclick="return getInput_value({{item.id}}, this); return false;">
                <span class="checkmark">
                  <div class="checkmark_circle"></div>
                  <div class="checkmark_stem"></div>
                  <div class="checkmark_kick"></div>
              </span>
              </a>
            
            <span class="pull-right">
              <a href="{% url 'shopping_cart:delete_item' item.id %}"  data-balloon="remove this item from cart" class="text-danger" onclick="return confirm_delete();">
                <i class="fas fa-trash"></i>
              </a>
            </span>
          </td>
         
        </tr>
      {% empty %}
        <tr>
          <td colspan= 3> You have not added any items yet.</td>
        </tr>
      {% endfor %}

     
      <tr>
        <td colspan=1 >
          <a href="{% url 'Webapp:order' %}" class="btn btn-warning pull-left">
            {% if order %}Add more Services{% else %}Add Services First {% endif %}
          </a> 
        </td>
        
         <td colspan=2>
          {% if order.get_cart_items %}
          <a href="{% url 'shopping_cart:export' %}" class="pull-right btn btn-primary" onclick="displayFunction()"> Generate Template</a>
          
          {% endif %}
        </td>
      </tr> 
      <tr id="result_tr" style="display: none;">
        <td colspan=2>
          {% if order.get_cart_items %}


          {% if messages %}
          {% for message in messages %}
              <div>
  <!--                | means OR operator-->
                  <strong>{{message|safe}}</strong>
              </div>
          {% endfor %}
      {% else %}
      {{orders}}
      <form action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <label for="file1"> Upload a file</label>
          <input type="file" id="file1" name="file">
          <small>Only accepts CSV files</small>
          <button type="submit" class=  "pull-right btn btn-primary">Upload CSV</button>
      </form>
      {% endif %}
      {% for profile in profiles %}
      {{profile.name}}
      {% endfor %}
          
          {% endif %}
        </td> 
      
      </tr>
    </table>
     
   </div>
  </div>
 </section>

{% block scripts %}
  {{ block.super }}
  <script>
  function confirm_delete(){
    return confirm("Do you want to remove this item from cart?");
  }
 function displayFunction(){
  var result_style = document.getElementById('result_tr').style;
  result_style.display = 'table-row';
 }

  function getInput_value(id,elemnt ){
   
    newelmnt= $(elemnt).closest('tr').find('input').val();
    window.location.href="http://127.0.0.1:8000/cart/service/update/first/second/".replace("first",id).replace("second",newelmnt)
    return false;

  }

  </script>
{% endblock scripts %}

 <!--==========================
    Footer
  ============================-->
  <footer id="footer" class="section-bg">
    <div class="footer-top">
      <div class="container">

        <div class="row">

          <div class="col-lg-6">

            <div class="row">

                <div class="col-sm-6">

                  <div class="footer-info">
                    <h3>The Nutrition Platform</h3>
                    <p>Analytical testing Services and support in food safety, food nutrition and related
                      agricultural applications.</p>
                  </div>

                 

                </div>

                <div class="col-sm-6">
                 

                  <div class="footer-links">
                    <h4>Contact Us</h4>
                    <p>
                      P.O Box 30709<br>
                      Nairobi 00100<br>
                      Kenya <br>
                      <strong>Phone:</strong> +254 20 422 3384<br>
                      <strong>Email:</strong> mycnutplatform@cgiar.org<br>
                    </p>
                  </div>

                  <div class="social-links">
                    <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
                    <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
                    <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
                    <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
                  </div>

                </div>

            </div>

          </div>

        

          

        </div>

      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong>BecA-ILRI</strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!--
          All the links in the footer should remain intact.
          You can delete the links only if you purchased the pro version.
          Licensing information: https://bootstrapmade.com/license/
          Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Rapid
        -->
        Designed using <a href="https://www.djangoproject.com/" target="_blank">Django</a>
      </div>
    </div>
  </footer><!-- #footer -->

{% endblock %}