NutriWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from Webapp import views

handler404 = 'Webapp.views.handler404'
handler500 = 'Webapp.views.handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

Webapp/urls.py
from django.urls import path
from Webapp import views

# SET THE NAMESPACE!
app_name = 'Webapp'

urlpatterns = [
    path('order/',views.order,name='order'),
    path('user_login/',views.user_login,name='user_login'),
    path('logout/',views.user_logout,name='user_logout'),
    path('register/',views.register,name='register'),
    path('', views.mainpage, name='services'),
    path('order/', views.order, name='order'),
    path('thanks/',views.thanks,name='thanks'),
    path('userinfo/',views.userinfo,name='userinfo'),
    path('db/',views.dbfront,name='dbfront'),
]

shopping_cart/urls.py
from django.conf.urls import url
from django.urls import path

from .views import (
    add_to_cart,
    order_details,
    delete_from_cart,
    update_item_number,
    export,
    
)

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^service/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^service/update/(?P<item_id>[-\w]+)/(?P<item_number>[-\w]+)/$', update_item_number, name='update_item'),
    path('export/',export,name='export'),

    
]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Nutrition Platform</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicons -->
  <link href="{% static "img/favicon.ico" %}" rel="icon">
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,500,600,700,700i|Montserrat:300,400,500,600,700" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

  <!-- Bootstrap CSS File -->
  <link href="{% static "lib/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="{% static "lib/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">
  <link href="{% static "lib/animate/animate.min.css" %}" rel="stylesheet">
  <link href="{% static "lib/ionicons/css/ionicons.min.css" %}" rel="stylesheet">
  <link href="{% static "lib/owlcarousel/assets/owl.carousel.min.css" %}" rel="stylesheet">
  <link href="{% static "lib/lightbox/css/lightbox.min.css" %}" rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="{% static "css/style.css" %}" rel="stylesheet">
<!-- custom stylesheet-->
  <link href= "{% static "css/base.css" %}"  rel="stylesheet">


</head>

<body>
  <!--==========================
  Header
  ============================-->
  <header id="header">

    <!-- Staff Navigation -->
    {% if user.is_staff %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
  <div class="container">
    <a class="navbar-brand" href="#">
          <img src="{% static "img/NutritionPlatformLogo.png" %}" alt="Logo"></a>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/db">Orders<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/admin/">DataBase</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
    {% endif %}
<!-- ========= End of Staff nav ============ -->

    <div id="topbar">
      <div class="container">
        <div class="social-links">
          <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
          <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
          <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
          <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
        </div>
      </div>
    </div>
<!-- NavBar -->
    <div class="container">

      <div class="logo float-left">
        <!-- Uncomment below if you prefer to use an image logo -->
        <h1 class="text-light"><a href="/" class="scrollto"><span>Nutrition</span></a></h1>
        <!-- <a href="#header" class="scrollto"><img src="img/logo.png" alt="" class="img-fluid"></a> -->
      </div>

      <nav class="main-nav float-right d-none d-lg-block">
        <ul>
          <li class="active"><a href="/">Home</a></li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="#">About us</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="/#about">About us</a>
              <a class="dropdown-item" href="/#services">Services</a>
              <a class="dropdown-item" href="/#why-us">Why Us</a>
              <a class="dropdown-item" href="/#clients">Our Clients</a>
              <a class="dropdown-item" href="/#team">The Team</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="/#faq">FAQs</a>
            </div>
          </li>          
          <li class="current"><a href="/order/">Make an Order</a></li>
          <li><a href="/#footer">Contact Us</a></li>
          <li><a href="{% url 'Webapp:register' %}">Register</a></li>
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
          <li class="nav-item dropdown profile">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="fa fa-user"></span><span>{{ request.user.username }}</span>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'shopping_cart:order_summary' %}">My Order</a> 
              <a class="dropdown-item" href="{% url 'shopping_cart:order_summary' %}">All Orders</a>              
          </div>
          </li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'Webapp:user_login' %}">Login</a></li>
          {% endif %}          
        </ul>
      </nav><!-- .main-nav -->
      
    </div>

  </header><!-- #header -->

  {% block body %}
  
  {% endblock %}

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
  <!-- Uncomment below i you want to use a preloader -->
  <!-- <div id="preloader"></div> -->

  <!-- JavaScript Libraries -->
  <script src="{% static "lib/jquery/jquery.min.js" %}"></script>
  <script src="{% static "lib/jquery/jquery-migrate.min.js" %}"></script>
  <script src="{% static "lib/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
  <script src="{% static "lib/easing/easing.min.js" %}"></script>
  <script src="{% static "lib/mobile-nav/mobile-nav.js" %}"></script>
  <script src="{% static "lib/wow/wow.min.js" %}"></script>
  <script src="{% static "lib/waypoints/waypoints.min.js" %}"></script>
  <script src="{% static "lib/counterup/counterup.min.js" %}"></script>
  <script src="{% static "lib/owlcarousel/owl.carousel.min.js" %}"></script>
  <script src="{% static "lib/isotope/isotope.pkgd.min.js" %}"></script>
  <script src="{% static "lib/lightbox/js/lightbox.min.js" %}"></script>
  <!-- Contact Form JavaScript File -->
  <script src="{% static "contactform/contactform.js" %}"></script>

  <!-- Template Main Javascript File -->
  <script src="{% static "js/main.js" %}"></script>

</body>
</html>

templates/dbfront.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>DB</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">	
<!--===============================================================================================-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand" href="/db">DB Example</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	  <span class="navbar-toggler-icon"></span>
	</button>
  
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
	  <ul class="navbar-nav mr-auto">
		<li class="nav-item active">
		  <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
		</li>
		<li class="nav-item active">
			<a class="nav-link" href="admin/">DataBase<span class="sr-only">(current)</span></a>
		  </li><li class="nav-item active">
			<a class="nav-link" href="/" target="_blank">Client Website <span class="sr-only">(current)</span></a>
		  </li>
		<li class="nav-item dropdown">
		  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			Important Links
		  </a>
		  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
			<a class="dropdown-item" href="#">Action</a>
			<a class="dropdown-item" href="#">Another action</a>
			<div class="dropdown-divider"></div>
			<a class="dropdown-item" href="#">Something else here</a>
		  </div>
		</li>
	  </ul>
	</div>
  </nav>
<!--===============================================================================================-->
</head>
<body class="container">

	{% block body %}
	<h3>Here's a summary of the Order records from our database</h3>

	<table class="table">
		<thead class="thead-dark">
		  <tr>
			<th scope="col">Order No.</th>
			<th scope="col">Date Recieved</th>
			<th scope="col">Clients</th>
			<th scope="col">No of Samples</th>
            <th scope="col">Sample Type</th>
            <th scope="col">Sample Reciever</th>
            <th scope="col">Analyis Required</th>
            <th scope="col">Remarks</th>
            <th scope="col">Stage</th>           
		  </tr>
		</thead>
		<tbody>

		{% for record in all_objects %}
		<tr>
			<th scope="row">{{ record.Order_Number }}</th>
			<td>{{ record.Date_recieved }}</td>
			<td >{{ record.Client }}</td>
            <td>{{ record.No_of_Samples }}</td>
            <td>{{ record.Sample_Type }}</td>
            <td>{{ record.Sample_Reciever }}</td>
            <td>{{ record.Analyis_Required }}</td>
            <td>{{ record.Remarks }}</td>
            <td>{{ record.Stage }}</td>            
		</tr>
		{% endfor %}
	</tbody>
	  </table>
      
{% endblock %}
<!--===============================================================================================-->	
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

templates/order.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Place an Order{% endblock %}
{% load static %}

{% block body %}

    <!--==========================
      Service Section
    ============================-->
    <section id="services" class="section-bg">
      <div class="container">
            <header class="section-header">
              <h3>Request For a Service</h3>
              <p>Click on a category below to expand and view more</p>
            </header>
          <div class="row">
            <ul id="services-list" class="wow fadeInUp services-row">
                  <li>
                    <a data-toggle="collapse" class="collapsed ion-ios-analytics-outline" href="#services1">Food safety <i class="ion-android-remove"></i></a>
                    <div id="services1" class="collapse" data-parent="#services-list">
                      <ul>
                        {% for service in services %}
                        {%if service.category == "food_safety" %}
                        <li>{{ service.description }}  &nbsp; 
                          {% if service in user.profile.services %}
                          You own this 
                          {% elif service in current_order_services%}
                          <a href="{% url 'shopping_cart:order_summary' %}" class="order-service">Go to Cart</a>
                          {%else%}
                          <a href="{% url 'shopping_cart:add_to_cart' service.id %}" 
                           class="order-service">Add Service</a>
                          {%endif%}
                          </li>
                          {%endif%}
                        {% endfor %}
                      </ul>
                    </div>
                  </li>
    

                <li>
                  <a data-toggle="collapse" href="#services2" class="collapsed ion-ios-bookmarks-outline">Food nutrition <i class="ion-android-remove"></i></a>
                  <div id="services2" class="collapse" data-parent="#services-list">
                    <ul>
                      {% for service in services %}
                      {%if service.category == "food_nutrition" %}
                      <li>{{ service.description }}  &nbsp; 
                        {% if service in user.profile.services %}
                        You own this 
                        {% elif service in current_order_services%}
                        <a href="{% url 'shopping_cart:order_summary' %}" class="order-service">Go to Cart</a>
                        {%else%}
                        <a href="{% url 'shopping_cart:add_to_cart' service.id %}" 
                         class="order-service">Add Service</a>
                        {%endif%}
                        </li>
                        {%endif%}
                      {% endfor %}
                    </ul>
                  </div>
                </li>

                <li>
                  <a data-toggle="collapse" href="#services3" class="collapsed ion-ios-paper-outline">Others <i class="ion-android-remove"></i></a>
                  <div id="services3" class="collapse" data-parent="#services-list">
                    <ul>
                      {% for service in services %}
                      {%if service.category == "others" %}
                      <li>{{ service.description }}  &nbsp; 
                        {% if service in user.profile.services %}
                        You own this 
                        {% elif service in current_order_services%}
                        <a href="{% url 'shopping_cart:order_summary' %}" class="order-service">Go to Cart</a>
                        {%else%}
                        <a href="{% url 'shopping_cart:add_to_cart' service.id %}" 
                         class="order-service">Add Service</a>
                        {%endif%}
                        </li>
                        {%endif%}
                      {% endfor %}
                    </ul>
                  </div>
                </li>

              <li>
                <a data-toggle="collapse" href="#services4" class="collapsed ion-ios-speedometer-outline">Training <i class="ion-android-remove"></i></a>
                <div id="services4" class="collapse" data-parent="#services-list">
                  <ul>
                    {% for service in services %}
                    {%if service.category == "training" %}
                    <li>{{ service.description }}  &nbsp; 
                      {% if service in user.profile.services %}
                      You own this 
                      {% elif service in current_order_services%}
                      <a href="{% url 'shopping_cart:order_summary' %}" class="order-service">Go to Cart</a>
                      {%else%}
                      <a href="{% url 'shopping_cart:add_to_cart' service.id %}" 
                       class="order-service">Add Service</a>
                      {%endif%}
                      </li>
                      {%endif%}
                    {% endfor %}
                  </ul>
                </div>
              </li>

          </ul>
          </div>
          </div>
    </section>
    <!-- #services -->

     <!--==========================
    Footer
  ============================-->
  <footer id="footer" class="section-bg">
    <div class="footer-top">
      <div class="container">

        <div class="row">

          <div class="col-lg-6">

            <div class="row">

                <div class="col-sm-6">

                  <div class="footer-info">
                    <h3>The Nutrition Platform</h3>
                    <p>Analytical testing Services and support in food safety, food nutrition and related
                      agricultural applications.</p>
                  </div>

                 

                </div>

                <div class="col-sm-6">
                 

                  <div class="footer-links">
                    <h4>Contact Us</h4>
                    <p>
                      P.O Box 30709<br>
                      Nairobi 00100<br>
                      Kenya <br>
                      <strong>Phone:</strong> +254 20 422 3384<br>
                      <strong>Email:</strong> mycnutplatform@cgiar.org<br>
                    </p>
                  </div>

                  <div class="social-links">
                    <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
                    <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
                    <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
                    <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
                  </div>

                </div>

            </div>

          </div>

        

          

        </div>

      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong>BecA-ILRI</strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!--
          All the links in the footer should remain intact.
          You can delete the links only if you purchased the pro version.
          Licensing information: https://bootstrapmade.com/license/
          Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Rapid
        -->
        Designed using <a href="https://www.djangoproject.com/" target="_blank">Django</a>
      </div>
    </div>
  </footer><!-- #footer -->

{% endblock %}

templates/registration.html
<!doctype html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Register{% endblock %}
{% block body %}

<br><br><br><br><br>
<section class="section-bg">
  <div class="row justify-content-center align-self-center">
    <div class="col-md-6 intro-info order-md-first order-last">
              <br><br><br><br><br><br>    
              <div class="container">
        {% if registered %}
          <h1>Thank you for registering!</h1>
        {% else %}
          <h1>Register Here</h1>
          <h3>Just fill out the form.</h3>
          <form class="lead" enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {% include 'bs4_form.html' with form=user_form %}
            <input type="submit" name="" value="Register">
          </form>
</div>
</div>
</div>
</section>
        
        {% endif %}






{% endblock %}

templates/update_info.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block title %}My Dashboard{% endblock title %}
{% block body %} 

<br><br><br><br><br><br>
            <section class="section-bg">
                            <div class="container">
                                <h3>We need more details abou you</h3>
                                <form method="POST">
                                        {% csrf_token %}
                                        {% include 'bs4_form.html' with form=form %}
                                    <input type="submit" name="" value="Update info">
                              </form>
                            </div>                
            </section>

{% endblock %}